image:
  repository: bwoodr01/nginx
  tag: 7176ba6
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
containerPorts:
  https: 8080
service:
  type: LoadBalancer
  ports:
    https: 443
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:663118211814:certificate/f77cd7ad-b251-470f-aff3-8a3faa12e4c"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: "test-subaccount-1.rr.mu"
  path: "/"
  pathType: "Prefix"
